classdef ExperimentPanel < aod.app.EventHandler
% Handles events generated by experiment add/remove interface
%
% Superclass:
%   EventHandler
%
% Constructor:
%   obj = aod.app.query.handlers.ExperimentPanel(parent)

% By Sara Patterson, 2023 (AOData)
% -------------------------------------------------------------------------

    methods 
        function obj = ExperimentPanel(parent)
            obj = obj@aod.app.EventHandler(parent);
        end
    end
end 