classdef ExperimentPanel < aod.app.EventHandler
% Handles events generated by experiment add/remove interface
%
% Superclass:
%   EventHandler
%
% Constructor:
%   obj = aod.app.query.handlers.ExperimentPanel(parent)

% By Sara Patterson, 2023 (AOData)
% -------------------------------------------------------------------------

    methods 
        function obj = ExperimentPanel(parent)
            obj = obj@aod.app.EventHandler(parent);
        end

        function handleRequest(obj, ~, evt)
            switch evt.EventType 
                case "AddExperiment"
                    expt = string(evt.Trigger.Items)';
                    expt = cat(1, expt, evt.Data.FileName);
                    evt.Trigger.Items = expt;
                    obj.Parent.removeButton.Enable = "on";
                case "RemoveExperiment"
                    expt = setdiff(evt.Trigger.Items, evt.Data.FileName);
                    evt.Trigger.Items = expt;
                    if isempty(expt)
                        obj.Parent.removeButton.Enable = "off";
                    end
            end 
            obj.passRequest(evt);
        end

    end
end 